/*

 POINTER.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char pointer[] =
{
  0x7E,0x7E,0xC3,0xFF,0xA5,0xC3,0x43,0xE7,
  0xC2,0xE7,0xA5,0xC3,0xA5,0xC3,0x43,0xE7,
  0xC2,0xE7,0xA5,0xC3,0xA5,0xC3,0x43,0xE7,
  0xC2,0xE7,0xA5,0xC3,0xA5,0xC3,0x43,0xE7
};

/* End of POINTER.C */
